#!/bin/bash
# Blue-Green Deployment script

echo "Deploying Blue version..."
kubectl apply -f messaging_app/blue_deployment.yaml

echo "Deploying Green version..."
kubectl apply -f messaging_app/green_deployment.yaml

echo "Applying Service..."
kubectl apply -f messaging_app/kubeservice.yaml

echo "Checking logs of Green version..."
kubectl logs -l app=django,version=green --tail=50
