apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    version: blue   # start with blue, later switch to green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
